{
 "title": "VictoriaMetrics - vmanomaly - anomaly statistics",
 "description": "Anomaly statistic dashboard for VictoriaMetrics Anomaly Detection (vmanomaly) v1.19.2 or higher",
 "tags": [ "vmanomaly" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "DS_VM",
    "label": "Data Source",
    "query": "victoriametrics-metrics-datasource"
   },
   { "name": "vmanomaly_prefix", "label": "Metrics Prefix" },
   { "name": "anomaly_score_threshold", "label": "Threshold", "query": "1.0" },
   {
    "name": "preset",
    "label": "Presets",
    "query": {
     "query": "label_values({__name__=\"${vmanomaly_prefix}anomaly_score\"},preset)"
    }
   },
   {
    "name": "scheduler_alias",
    "label": "Schedulers",
    "query": {
     "query": "label_values({__name__=\"${vmanomaly_prefix}anomaly_score\", preset=~\"$preset\"},scheduler_alias)"
    }
   },
   {
    "name": "model_alias",
    "label": "Models",
    "query": {
     "query": "label_values({__name__=\"${vmanomaly_prefix}anomaly_score\", preset=~\"$preset\", scheduler_alias=~\"$scheduler_alias\"},model_alias)"
    }
   },
   {
    "name": "query_key",
    "label": "Queries",
    "query": {
     "query": "label_values({__name__=\"${vmanomaly_prefix}anomaly_score\", preset=~\"$preset\", scheduler_alias=~\"$scheduler_alias\", model_alias=~\"$model_alias\"},for)"
    }
   },
   {
    "name": "groupby",
    "label": "Group by",
    "query": {
     "query": "label_names(${vmanomaly_prefix}anomaly_score)"
    }
   },
   { "name": "anomaly_share", "label": "Min. Anomaly%", "query": "5" },
   {
    "name": "output_series",
    "label": "Show series",
    "query": "y, yhat, yhat_lower, yhat_upper"
   },
   { "name": "adhoc_filters", "label": "Ad hoc filters" }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Hints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "description": "This section highlights hints to make full use of the dashboard",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "This dashboard shows **[anomaly score](https://docs.victoriametrics.com/anomaly-detection/faq/#what-is-anomaly-score)** statistics produced by [`vmanomaly`](https://victoriametrics.com/products/enterprise/anomaly-detection/) and stored in \"${DS_VM:text}\" datasource.\n\nTimezone: `$__timezone`\n\n<br>\n\n#### Usage Hints:\n- Hover over the **(i) icons** in the top-right corner of each visualization and variable to see a detailed description of its specifics.\n- **Dashboard-level filters** apply to all visualizations.\n  - The most generic filters are already added, e.g. `model_alias`, `scheduler_alias`, <br>which are the labels that all `anomaly_score` metrics have by default\n  - To filter on one or more labels, use `Ad hoc filters` [ad hoc Grafana filter](https://grafana.com/docs/grafana/latest/dashboards/use-dashboards/#filter-dashboard-data).\n- Adjust `Metrics prefix` (current = `${vmanomaly_prefix}`) according to output format, defined in `writer.metric_format` [config section](https://docs.victoriametrics.com/anomaly-detection/components/writer/?highlight=metric_format#config-parameters)\n  - e.g. if your `writer.metric_format.__name__` was set to `vmanomaly_$VAR`, set the prefix to `vmanomaly_` string.\n- The **`Group by`** dashboard filter allows you to segment visualizations based on selected labels.\n  - For example, setting it to `model_alias` will create separate sub-visualizations for each unique model alias.\n  - This helps in analyzing anomaly patterns across different dimensions.\n- The **`Threshold`** dashboard constant (default: `1.0`, current: `$anomaly_score_threshold`) determines anomaly classification:\n  - **Non-anomalous** data points: `anomaly_score` ≤ `Threshold`\n  - **Anomalous** data points: `anomaly_score` > `Threshold`\n  - Set the threshold value consistently with your **alerting rules** for accurate anomaly detection.\n- The **`Min Anomaly%`** dashboard constant helps to filter the visualizations in **Local Anomaly Score Statistics** dashboard section,<br>leaving only timeseries with % of anomalies over time > selected value (`$anomaly_share`%)\n- The **`Show series`** dashboard custom multi-valued list allows to specify what [vmanomaly output](https://docs.victoriametrics.com/anomaly-detection/components/models/#vmanomaly-output) series <br>to plot on \"local anomaly score statistics\" dashboard sections <br>(defaults to `y` - raw metric values model saw during prediction phase)"
     }
    }
   ]
  },
  {
   "title": "Global Anomaly Score Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "type": "text",
   "description": "This section presents aggregated (by `$groupby`) **[anomaly score](https://docs.victoriametrics.com/anomaly-detection/faq/#what-is-anomaly-score)** statistics for active instances of [VictoriaMetrics Anomaly Detection](https://victoriametrics.com/products/enterprise/anomaly-detection/) (`vmanomaly`).",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
   "options": {
    "content": "This section presents aggregated (by `${groupby}`) **[anomaly score](https://docs.victoriametrics.com/anomaly-detection/faq/#what-is-anomaly-score)** statistics for active instances of [VictoriaMetrics Anomaly Detection](https://victoriametrics.com/products/enterprise/anomaly-detection/) (`vmanomaly`). <br>`Min.Anomaly%` filter **doesn't affect** the results of this section."
   }
  },
  {
   "title": "Anomaly Score Statistics, grouped by `$groupby`",
   "type": "table",
   "description": "Statistics (min, max, quantiles, share and cnt of scores > `Threshold`=`$anomaly_score_threshold`) for [anomaly scores](https://docs.victoriametrics.com/anomaly-detection/faq/#what-is-anomaly-score), given dashboard-level filters and (optional) `Group by`=`$groupby` grouping applied as additional columns, if set",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count({__name__=\"${vmanomaly_prefix}anomaly_score\", preset=~\"${preset}\", scheduler_alias=~\"${scheduler_alias}\", model_alias=~\"${model_alias}\", for=~\"${query_key}\", ${adhoc_filters}}[$__range]) by ($groupby)",
     "legendFormat": "series.cnt"
    },
    {
     "expr": "sum(count_over_time({__name__=\"${vmanomaly_prefix}anomaly_score\", preset=~\"${preset}\", scheduler_alias=~\"${scheduler_alias}\", model_alias=~\"${model_alias}\",  for=~\"${query_key}\", ${adhoc_filters}}[$__range])) by ($groupby)",
     "legendFormat": "points.cnt"
    },
    {
     "expr": "sum(count_gt_over_time({__name__=\"${vmanomaly_prefix}anomaly_score\", preset=~\"${preset}\", scheduler_alias=~\"${scheduler_alias}\", model_alias=~\"${model_alias}\",  for=~\"${query_key}\", ${adhoc_filters}}[$__range], $anomaly_score_threshold)) by ($groupby)",
     "legendFormat": "anomaly.cnt"
    },
    {
     "expr": "avg(share_gt_over_time({__name__=\"${vmanomaly_prefix}anomaly_score\", preset=~\"${preset}\", scheduler_alias=~\"${scheduler_alias}\", model_alias=~\"${model_alias}\",  for=~\"${query_key}\", ${adhoc_filters}}[$__range], $anomaly_score_threshold)) by ($groupby)",
     "legendFormat": "anomaly.%"
    },
    {
     "expr": "min({__name__=\"${vmanomaly_prefix}anomaly_score\", preset=~\"${preset}\", scheduler_alias=~\"${scheduler_alias}\", model_alias=~\"${model_alias}\",  for=~\"${query_key}\", ${adhoc_filters}}[$__range]) by ($groupby)",
     "legendFormat": "score.min"
    },
    {
     "expr": "quantile(0.25, {__name__=\"${vmanomaly_prefix}anomaly_score\", preset=~\"${preset}\", scheduler_alias=~\"${scheduler_alias}\", model_alias=~\"${model_alias}\",  for=~\"${query_key}\", ${adhoc_filters}}[$__range]) by ($groupby)",
     "legendFormat": "score.q25"
    },
    {
     "expr": "quantile(0.5, {__name__=\"${vmanomaly_prefix}anomaly_score\", preset=~\"${preset}\", scheduler_alias=~\"${scheduler_alias}\", model_alias=~\"${model_alias}\",  for=~\"${query_key}\", ${adhoc_filters}}[$__range]) by ($groupby)",
     "legendFormat": "score.q50"
    },
    {
     "expr": "quantile(0.75, {__name__=\"${vmanomaly_prefix}anomaly_score\", preset=~\"${preset}\", scheduler_alias=~\"${scheduler_alias}\", model_alias=~\"${model_alias}\",  for=~\"${query_key}\", ${adhoc_filters}}[$__range]) by ($groupby)",
     "legendFormat": "score.q75"
    },
    {
     "expr": "quantile(0.99, {__name__=\"${vmanomaly_prefix}anomaly_score\", preset=~\"${preset}\", scheduler_alias=~\"${scheduler_alias}\", model_alias=~\"${model_alias}\",  for=~\"${query_key}\", ${adhoc_filters}}[$__range]) by ($groupby)",
     "legendFormat": "score.q99"
    },
    {
     "expr": "max({__name__=\"${vmanomaly_prefix}anomaly_score\", preset=~\"${preset}\", scheduler_alias=~\"${scheduler_alias}\", model_alias=~\"${model_alias}\", for=~\"${query_key}\", ${adhoc_filters}}[$__range]) by ($groupby)",
     "legendFormat": "score.max"
    }
   ]
  },
  {
   "title": "% of Anomalies over time (threshold = $anomaly_score_threshold), grouped by `$groupby`",
   "type": "timeseries",
   "description": "% of anomalous data points over selected time range, given anomaly threshold `Threshold`=`$anomaly_score_threshold` and the other dashboard-level filters.",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(share_gt_over_time({__name__=\"${vmanomaly_prefix}anomaly_score\", preset=~\"${preset}\", scheduler_alias=~\"${scheduler_alias}\", model_alias=~\"${model_alias}\", for=~\"${query_key}\", ${adhoc_filters}}[$__range], $anomaly_score_threshold)) by ($groupby)",
     "legendFormat": "% over time {{$groupby}}"
    }
   ]
  },
  {
   "title": "Anomaly score (> $anomaly_score_threshold) distribution, grouped by `$groupby`",
   "type": "histogram",
   "description": "Distribution of [anomaly scores](https://docs.victoriametrics.com/anomaly-detection/faq/#what-is-anomaly-score) over selected time range, given anomaly threshold `Threshold` and the other dashboard-level filters.",
   "gridPos": { "h": 18, "w": 10, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg({__name__=\"${vmanomaly_prefix}anomaly_score\", preset=~\"${preset}\", scheduler_alias=~\"${scheduler_alias}\", model_alias=~\"${model_alias}\", for=~\"${query_key}\", ${adhoc_filters}}[$__range] > $anomaly_score_threshold) by ($groupby)",
     "legendFormat": "score distribution, {{$groupby}}"
    }
   ]
  },
  {
   "title": "q99 anomaly score over time (threshold = $anomaly_score_threshold), grouped by `$groupby`",
   "type": "timeseries",
   "description": "99th quantile anomaly score over selected time range, given anomaly `Threshold`=`$anomaly_score_threshold` and the other dashboard-level filters.",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "quantile(0.99, {__name__=\"${vmanomaly_prefix}anomaly_score\", preset=~\"${preset}\", scheduler_alias=~\"${scheduler_alias}\", model_alias=~\"${model_alias}\", for=~\"${query_key}\", ${adhoc_filters}}[$__range]) by ($groupby)",
     "legendFormat": "score q99 {{$groupby}}"
    },
    {
     "expr": "$anomaly_score_threshold",
     "legendFormat": "Threshold=$anomaly_score_threshold"
    }
   ]
  },
  {
   "title": "Local Anomaly Score Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "description": "This section holds raw (timeseries-wise) **[anomaly score](https://docs.victoriametrics.com/anomaly-detection/faq/#what-is-anomaly-score)** statistics for active instances of [VictoriaMetrics Anomaly Detection](https://victoriametrics.com/products/enterprise/anomaly-detection/) (`vmanomaly`).",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 30 },
     "options": {
      "content": "This section holds raw (timeseries-wise)  **[anomaly score](https://docs.victoriametrics.com/anomaly-detection/faq/#what-is-anomaly-score)** statistics produced by [VictoriaMetrics Anomaly Detection](https://victoriametrics.com/products/enterprise/anomaly-detection/) (`vmanomaly`). <br>`Min.Anomaly%` filter affect the results of this section."
     }
    },
    {
     "title": "Anomalous Time Series",
     "type": "table",
     "description": "This table holds the labelset and the respective anomaly% (share of raw datapoints over a selected time range that have anomaly score > `Threshold` = `$anomaly_score_threshold`) for individual timeseries, additionally filtered by min anomaly  filter = `$anomaly_share` %",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "share_gt_over_time({__name__=\"${vmanomaly_prefix}anomaly_score\", preset=~\"${preset}\", scheduler_alias=~\"${scheduler_alias}\", model_alias=~\"${model_alias}\", for=~\"${query_key}\"}[$__range], $anomaly_score_threshold) >= ($anomaly_share/100)",
       "legendFormat": "anomaly.%"
      }
     ]
    },
    {
     "title": "Anomalous Time Series",
     "type": "timeseries",
     "description": "[Anomaly scores](https://docs.victoriametrics.com/anomaly-detection/faq/#what-is-anomaly-score) over time for individual timeseries, given dashboard filters",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "{__name__=\"${vmanomaly_prefix}anomaly_score\", preset=~\"${preset}\", scheduler_alias=~\"${scheduler_alias}\", model_alias=~\"${model_alias}\", for=~\"${query_key}\"}[$__range] and range_last(\n  share_gt_over_time(\n    {__name__=\"${vmanomaly_prefix}anomaly_score\", preset=~\"${preset}\", scheduler_alias=~\"${scheduler_alias}\", model_alias=~\"${model_alias}\", for=~\"${query_key}\"}[$__range], \n    $anomaly_score_threshold\n  ) >= ($anomaly_share / 100)\n) ",
       "legendFormat": "__auto"
      },
      {
       "expr": "$anomaly_score_threshold",
       "legendFormat": "Threshold=$anomaly_score_threshold"
      }
     ]
    },
    {
     "title": "Raw Metric Values ($output_series)",
     "type": "timeseries",
     "description": "Raw metric values which correspond to generated above [anomaly scores](https://docs.victoriametrics.com/anomaly-detection/faq/#what-is-anomaly-score) for easier debugging. Different series from [vmanomaly output](https://docs.victoriametrics.com/anomaly-detection/components/models/#vmanomaly-output) can be shown, including `y` (raw metric value model saw at prediction time), `yhat` (model predictions), `yhat_lower` and `yhat_upper` (respective model predictions' boundaries).\n\n**Note:** This panel works only if `writer.metric_format.for` was properly set in `vmanomaly` config + `provide_series` arg of respective [model](https://docs.victoriametrics.com/anomaly-detection/components/models/#provide-series) included `y` column, so for each timeseries seen not only `anomaly_score` metric was generated, but also `y` (actual values model saw during inference). See [the guide section for the details](https://docs.victoriametrics.com/anomaly-detection/presets/#default)",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "{__name__=~\"${vmanomaly_prefix}${output_series}\", preset=~\"${preset}\", scheduler_alias=~\"${scheduler_alias}\", model_alias=~\"${model_alias}\", for=~\"${query_key}\"}[$__range] and range_last(\n  share_gt_over_time(\n    {__name__=\"${vmanomaly_prefix}anomaly_score\", preset=~\"${preset}\", scheduler_alias=~\"${scheduler_alias}\", model_alias=~\"${model_alias}\", for=~\"${query_key}\"}[$__range], \n    $anomaly_score_threshold\n  ) >= ($anomaly_share / 100)\n) ",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}